spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fantasy_fight
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      format-sql: true